var hints = (function () {
    var colors = [
        "LightGoldenRodYellow",
        "MediumSpringGreen",
        "MediumAquaMarine",
        "MediumSlateBlue",
        "MediumTurquoise",
        "MediumVioletRed",
        "CornflowerBlue",
        "BlanchedAlmond",
        "DarkOliveGreen",
        "LightSlateGray",
        "LightSlateGrey",
        "LightSteelBlue",
        "MediumSeaGreen",
        "DarkGoldenRod",
        "DarkSlateBlue",
        "DarkSlateGray",
        "DarkSlateGrey",
        "DarkTurquoise",
        "LavenderBlush",
        "LightSeaGreen",
        "PaleGoldenRod",
        "PaleTurquoise",
        "PaleVioletRed",
        "RebeccaPurple",
        "AntiqueWhite",
        "DarkSeaGreen",
        "LemonChiffon",
        "LightSkyBlue",
        "MediumOrchid",
        "MediumPurple",
        "MidnightBlue",
        "DarkMagenta",
        "DeepSkyBlue",
        "FloralWhite",
        "ForestGreen",
        "GreenYellow",
        "LightSalmon",
        "LightYellow",
        "NavajoWhite",
        "SaddleBrown",
        "SpringGreen",
        "YellowGreen",
        "Aquamarine",
        "BlueViolet",
        "Chartreuse",
        "DarkOrange",
        "DarkOrchid",
        "DarkSalmon",
        "DarkViolet",
        "DodgerBlue",
        "GhostWhite",
        "LightCoral",
        "LightGreen",
        "MediumBlue",
        "PapayaWhip",
        "PowderBlue",
        "SandyBrown",
        "WhiteSmoke",
        "BurlyWood",
        "AliceBlue",
        "CadetBlue",
        "Chocolate",
        "DarkGreen",
        "DarkKhaki",
        "FireBrick",
        "Gainsboro",
        "GoldenRod",
        "IndianRed",
        "LawnGreen",
        "LightBlue",
        "LightCyan",
        "LightGray",
        "LightGrey",
        "LightPink",
        "LimeGreen",
        "MintCream",
        "MistyRose",
        "OliveDrab",
        "OrangeRed",
        "PaleGreen",
        "PeachPuff",
        "RosyBrown",
        "RoyalBlue",
        "SlateBlue",
        "SlateGray",
        "SlateGrey",
        "SteelBlue",
        "Turquoise",
        "Cornsilk",
        "DarkBlue",
        "DarkCyan",
        "DarkGray",
        "DarkGrey",
        "DeepPink",
        "HoneyDew",
        "Lavender",
        "Moccasin",
        "SeaGreen",
        "SeaShell",
        "Crimson",
        "DarkRed",
        "DimGray",
        "DimGrey",
        "Fuchsia",
        "HotPink",
        "Magenta",
        "OldLace",
        "SkyBlue",
        "Thistle",
        "Bisque",
        "Indigo",
        "Maroon",
        "Orange",
        "Orchid",
        "Purple",
        "Salmon",
        "Sienna",
        "Silver",
        "Tomato",
        "Yellow",
        "Violet",
        "Coral",
        "Brown",
        "Black",
        "Beige",
        "Azure",
        "Green",
        "Ivory",
        "Khaki",
        "Linen",
        "Olive",
        "Wheat",
        "White",
        "Aqua",
        "Blue",
        "Cyan",
        "Gold",
        "Gray",
        "Grey",
        "Lime",
        "Navy",
        "Peru",
        "Pink",
        "Plum",
        "Snow",
        "Teal",
        "Red",
        "Tan"
    ];

    var defaultList = [
        "inherit",
        "initial",
        "auto",
        "none"
    ];

    var display = [
        "table-column-group",
        "table-footer-group",
        "table-header-group",
        "table-row-group",
        "table-caption",
        "inline-block",
        "inline-table",
        "table-column",
        "inline-flex",
        "table-cell",
        "list-item",
        "table-row",
        "inherit",
        "initial",
        "inline",
        "run-in",
        "block",
        "table",
        "flex",
        "none"
    ];

    return {
        "padding-bottom": defaultList,
        "margin-bottom": defaultList,
        "padding-right": defaultList,
        "border-width": defaultList,
        "padding-left": defaultList,
        "margin-right": defaultList,
        "background-color": colors,
        "padding-top": defaultList,
        "margin-left": defaultList,
        "margin-top": defaultList,
        "border-bottom": colors,
        "border-color": colors,
        "border-right": colors,
        "opacity": defaultList,
        "outline": defaultList,
        "padding": defaultList,
        "border-left": colors,
        "margin": defaultList,
        "background": colors,
        "border-top": colors,
        "display": display,
        "border": colors,
        "color": colors
    };
})();